### ISSUE TITLE
503 ERROR

### ISSUE THREAD

**Issue by DimaShep** [aws-samples/amazon-cloudfront-with-s3-multi-region-access-points#3]
Don't work, I get error:

503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: hiP1wRlybC_okraZxuX9rxaDKgTtBBOJ-e1_Ae2qh3QrGCtZzIfKtg==

**Comment by RomanCRS** [comment]
I had the same issue, but only when I was using Lambda Python 3.9. It works fine with Python 3.8
The original error was:
----
[ERROR] AttributeError: module 'botocore.crt' has no attribute 'auth'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 65, in lambda_handler
    auth_headers = SigV4AWrapper().get_auth_headers(method, endpoint, data, region, service, cf_read_only_headers)
  File "/var/task/lambda_function.py", line 24, in get_auth_headers
    sigv4a = crt.auth.CrtS3SigV4AsymAuth(self._session.get_credentials(), service, region)

**Comment by langhorstg316** [comment]
I followed the instructions and still getting the same 503? I am using 3.8 in cloudformation template. I even did pip install with python-version set to 3.8. Any other ideas how to make this work or troubleshoot? Nothing is coming in cloudwatch?

**Comment by verysamuel** [comment]
To shed slightly more light on this issue.

When running the Lambda manually (using Python 3.11), I get this error:
```json
{
  "errorMessage": "Unable to import module 'main': cannot import name 'awscrt' from 'botocore.compat' (/var/lang/lib/python3.11/site-packages/botocore/compat.py)",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "f5ee8ffe-6bc6-4097-ae88-6ad63ad1d341",
  "stackTrace": []
}
```

This would explain the 503s.

I have tried various dependencies like `botocore[crt]` as alternatives. No luck.

Perhaps either @lovaarte or @rprentyaws could shed some light on this issue? I'd really like to get this pattern working 🙏

Side note:
I am interested in getting this working with Python 3.11 for the very long term maintainability of this solution.

**Comment by raftutak** [comment]
@verysamuel any luck? I'm facing exactly the same issue.

**Comment by cheedallarajesh** [comment]
I ran into same error: `module 'botocore.crt' has no attribute 'auth'`

After investigating the issue, figured out that there's some conflict with the packages. So here is what I did:

I used GitHub copilot and regenerated the code and added some logs. 
I've tested it and see that the request is now being signed using sig4 auth.

You can find the updated in my personal repo. (I did not submitted a merge as I am not entirely sure if I can do that after making use of GitHub Copilot :face_with_peeking_eye: :shushing_face: )
https://github.com/cheedallarajesh/amazon-cloudfront-with-s3-multi-region-access-points/tree/main/lambda

both [lambda_function.py](https://github.com/cheedallarajesh/amazon-cloudfront-with-s3-multi-region-access-points/blob/main/lambda/lambda_function.py) and [requirements.txt](https://github.com/cheedallarajesh/amazon-cloudfront-with-s3-multi-region-access-points/blob/main/lambda/requirements.txt) are updated accordingly. 

`Please check the commit message for the lambda response showing signed request.`

**Comment by cheedallarajesh** [comment]
I was able to get this working. Here is what I did to resolve it:

1. The requirements.txt is referring to versions which needs to update to latest
> awscrt==0.19.10
boto3==1.28.0
botocore==1.31.0
requests==2.31.0

`pip install boto3 botocore awscrt  -t /package`

2. As I am on Windows, for some reason the awscrt though I see in the packages folder, it is not getting recognized. So, I used Ubuntu (WSL) and downloaded all the packages and latest ones to ./packages folder.
3. I included all the modules at the lambda_function.py level (root level). This may not be required but for some reason or maybe its lambda@edge, I couldn't get it work by keeping modules in /packages folder.

The key is, after having right versions of modules downloaded (in ubuntu environment) I could able to work it.

4. Here's my imports:

```python
import boto3
import botocore
from botocore import awsrequest
from botocore.crt.auth import CrtS3SigV4AsymAuth
import awscrt.auth
import logging
```
5. Checked below line 
https://github.com/aws-samples/amazon-cloudfront-with-s3-multi-region-access-points/blob/03a3a6f8c2b4ce71f57b979d21434772f662d561/lambda/lambda_function.py#L24

to this> with respect to updated imports

```python 
sigv4a = CrtS3SigV4AsymAuth(self._session.get_credentials(), service, region)
```

**Comment by jyuno426** [comment]
> ## I had the same issue, but only when I was using Lambda Python 3.9. It works fine with Python 3.8
> The original error was:
> [ERROR] AttributeError: module 'botocore.crt' has no attribute 'auth' Traceback (most recent call last): File "/var/task/lambda_function.py", line 65, in lambda_handler auth_headers = SigV4AWrapper().get_auth_headers(method, endpoint, data, region, service, cf_read_only_headers) File "/var/task/lambda_function.py", line 24, in get_auth_headers sigv4a = crt.auth.CrtS3SigV4AsymAuth(self._session.get_credentials(), service, region)

Just use python 3.8 and follow the README. It perfectly works.
